runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_ENV: local   # or production
  APP_LOG: errorlog
  APP_KEY: base64:DZiM1EfHU98zy5LV1zvBOKr7rJHePI51T+c/jl0qGjk=
  STORAGE_DIR: /tmp
  APP_DEBUG : true # or false

#follow the part of the tutorial on setting up your SQL database
DB_CONNECTION: mysql
DB_HOST: localhost
DB_DATABASE: truetaste-2-db-instance
DB_USERNAME: root
DB_PASSWORD: password
DB_SOCKET: /cloudsql/true-taste-2:us-central1:truetaste-2-db-instance 


MAIL_DRIVER: smtp
MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: truetaste2018@gmail.com
MAIL_PASSWORD: Truetaste@123
MAIL_ENCRYPTION: tls

beta_settings:
   # for Cloud SQL, set this value to the Cloud SQL connection name,
   # e.g. "project:region:cloudsql-instance"
   cloud_sql_instances: true-taste-2:us-central1:truetaste-2-db-instance